services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=drink_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - django_media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=drink_db
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    
volumes:
  postgres_data:
  django_media: